### ISSUE TITLE
Error getting subreddit lists

### ISSUE THREAD

**Issue by hxreborn** [induna-crewneck/Reddit-Lemmy-Migrator#3]
OS: Windows 10
Python version:  3.11.4
Chromedriver: 114.0.5735.90
159 subs accesible via chrome (HOME FEED SUBREDDITS (159))

`[0712/173557.334:INFO:CONSOLE(0)] "[.WebGL-00003AE80224A300]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels", source: https://old.reddit.com/subreddits/ (0)
[0712/173557.692:INFO:CONSOLE(29)] "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.", source: https://www.googleadservices.com/pagead/conversion.js (29)
[0712/173559.765:INFO:CONSOLE(29)] "Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.", source: https://www.googleadservices.com/pagead/conversion.js (29)
        Reddit login data valid.
`

Any help is appreciated

**Comment by hxreborn** [comment]
Worked flawlessly on my kde neon setup, i forgot to change the language to english on my reddit account, although i didnt get that error, maybe it was it. Will try ASAP on another windows install

**Comment by induna-crewneck** [comment]
It shouldn't work on non-english accounts because it looks for the "multireddit of your subscriptions" text (or something like that). I updated the code though with changes in many places, maybe it works now

**Comment by hxreborn** [comment]
Just tested it and still get the same error on Windows, but maybe it is just my Windows installation, who really knows

**Comment by induna-crewneck** [comment]
Implemented an autoinstaller for chromedriver in 1.4. Maybe it will work for you now?

**Comment by induna-crewneck** [comment]
Closed due to no response

**Comment by hxreborn** [comment]
Sorry for the late response, I was on vacation with no access to a windows system. It seems the issue is fixed, somehow it does not work for me, but the error is from their infrastructure

[proof here](https://i.imgur.com/II6s9k1.png)

Anyway, people that is using lemmy usually pick up a good operating system, so this issue is closed

Thank you for all your work
